name: CI
# The pipeline is triggered on:
#  - PR to master (code_quality_checks only)
#  - Push to master (full cycle)
#  - PR comment "/build-images" (code_quality_checks + build images)
#  - PR comment "/build-pipeline" (code_quality_checks + build kfp pipeline)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  issue_comment:
    types: [created]

env:
  ACR_REGISTRY: "k8scc01covidmlopsacr"
  ACR_REPOSITORY: "mlops"

jobs:
  code_quality_checks:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/build-pipeline') || contains(github.event.comment.body, '/build-images') || github.event_name != 'issue_comment'
    outputs:
      event_sha: ${{ env.event_sha }}
    steps:
      - uses: actions/checkout@v2
      - name: GetPRSHA
        if: github.event_name == 'issue_comment'
        run: echo "::set-env name=event_sha::+refs/pull/${{ github.event.issue.number }}/merge"
      - name: GetREFSHA
        if: github.event_name != 'issue_comment'
        run: echo "::set-env name=event_sha::${{ github.ref }}"
      - if: github.event_name == 'issue_comment'
        name: Checkout PR code
        run: |
          git fetch origin ${{ env.event_sha }}
          git checkout FETCH_HEAD
      - uses: TrueBrain/actions-flake8@master
        if: "true"
        with:
          path: "pipeline"
      - uses: TrueBrain/actions-flake8@master
        if: "true"
        with:
          path: "containers"

  build_images:
    runs-on: ubuntu-latest
    needs: code_quality_checks
    if: github.event_name == 'push' || github.event_name == 'issue_comment'
    steps:
      - name: Build Databricks Notebook Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: databricks-notebook
          folder: containers/databricks

      - name: Build TensorFlow Preprocess Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: tensorflow-preprocess
          folder: containers/tensorflow-preprocess

      - name: Build Register KF Artifacts Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: register-kubeflow-artifacts
          folder: containers/register-kubeflow-artifacts

      - name: Build Register AML Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: register-aml
          folder: containers/register-aml

      - name: Build Register MLFlow Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: register-mlflow
          folder: containers/register-mlflow

      - name: Build TensorFlow Training Image
        if: github.event_name == 'push' || contains(github.event.comment.body, '/build-images')
        uses: statcan/actions/acr-task@master
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PWD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ env.ACR_REGISTRY }}
          repository: ${{ env.ACR_REPOSITORY }}
          repository_crds: ${{ secrets.REPOSITORY_CRDS }}
          branch: ${{ needs.code_quality_checks.outputs.event_sha }}
          tag: latest
          image: tensorflow-training
          folder: containers/tensorflow-training

  build_kfp_pipeline:
    env:
      DATASETS: "https://aiadvocate.blob.core.windows.net/public/tacodata.zip"

    runs-on: ubuntu-latest
    needs: [code_quality_checks, build_images]
    if: github.event_name == 'push' || github.event_name == 'issue_comment' && contains(github.event.comment.body, '/build-pipeline')
    steps:
      - uses: actions/checkout@v2

      - if: github.event_name == 'issue_comment'
        name: Checkout PR code
        run: |
          git fetch origin ${{ needs.code_quality_checks.outputs.event_sha }}
          git checkout FETCH_HEAD

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          pip3 install "git+https://github.com/statcan/pipelines@db46df74bb3d37092d440bb2eb62d9e90b403c81#egg=kfp&subdirectory=sdk/python" adal --upgrade

      - name: Build KF Pipeline
        run: python train/cnn.py
        working-directory: pipeline
        env:
          PR_NUM: ${{ github.event.issue.number }}

      - name: Publish/Upload KF Pipeline
        env:
          KFP_PIPELINE_NAME: ${{ secrets.KFP_PIPELINE_NAME }}
          KFP_HOST: ${{ secrets.KFP_HOST }}
          RUN_ID: ${{ github.run_id }}
        run: |
          export PIPELINE_ID=$(python publish.py --run_id $RUN_ID \
                                                          --pipeline_name "$KFP_PIPELINE_NAME" \
                                                          --kfp_host $KFP_HOST \
                                                          --tenant ${{ secrets.tenant }} \
                                                          --service_principal ${{ secrets.SERVICE_PRINCIPAL }} \
                                                          --sp_secret ${{ secrets.SERVICE_PRINCIPAL_PWD }} \
                                                          --sp_audience ${{ secrets.SERVICE_PRINCIPAL_AUDIENCE }} \
                                                          --pipeline_file_path "train/cnn.py.tar.gz" 2>&1 >/dev/null)
          echo "pipeline id: $PIPELINE_ID"
          echo "::set-env name=PUBLISHED_PIPELINE_ID::$PIPELINE_ID"
        working-directory: pipeline

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: kfp-pipeline
          path: "pipeline/train/cnn.py.tar.gz"

      - name: Run Pipeline ID
        run: |
          python run.py --kfp_host ${{ secrets.KFP_HOST }} \
                                  --resource_group ${{ secrets.AML_RESOURCE_GROUP }} \
                                  --workspace ${{ secrets.AML_WORKSPACE }} \
                                  --pipeline_id $PUBLISHED_PIPELINE_ID \
                                  --run_name "${{ secrets.KFP_PIPELINE_NAME }}" \
                                  --tenant ${{ secrets.tenant }} \
                                  --service_principal ${{ secrets.SERVICE_PRINCIPAL }} \
                                  --sp_secret ${{ secrets.SERVICE_PRINCIPAL_PWD }} \
                                  --sp_audience ${{ secrets.SERVICE_PRINCIPAL_AUDIENCE }} \
                                  --datasets $DATASETS
        working-directory: pipeline
